import React from 'react';
import { ReactComponent as SettingIcon } from '../../../assets/svg/Settings.svg';
import { ReactComponent as ShowIcon } from '../../../assets/svg/Show.svg';
import { ReactComponent as Creator_tokenIcon } from '../../../assets/svg/Creator_token.svg';


// import { ReactComponent as CancelIcon } from '../../../assets/svg/Cancel.svg';
// import { ReactComponent as CancelIcon } from '../../../assets/svg/Cancel.svg';


export  const mapData =  [
  {
    'title' : '2023 Q1',
    'content' : [
      {
        'subTitle' : '1.New Exchange Listings',
        'description' : 'Outreach & discussions with additional cryptocurrency exchanges to provide users with more options for trading the JOY token.',
        'icon' : <SettingIcon/>,
      },
      {
        'subTitle' : '2.Creator tokens',
        'description' : 'Creator tokens is a key financial, value capture and community growth primitive unlocked by Joystream. It allows creator to issue a fungible token which captures revenue generated by their channel, and distributes a share of it pro-rate to token holders. There are also complem...',
        'icon' : <Creator_tokenIcon/>,
      },
      {
        'subTitle' : '3.Content Infrastructure: Visibility',
        'description' : 'With greater utilization and scale, it has become clear that there is a need for better visibility into errors and performance levels at different layers of the infrastructure. This means both capturing data from the consumer and infrastructure layer, and also synthetic...',
        'icon' : <ShowIcon/>,
      },
      {
        'subTitle' : '4.Project Overview Dashboard',
        'description' : ' purpose built data-driven dashboard to explain the project’s current status, growth and market positioning. This will be on the main project website and make it easy & quick for people to understand how the platform is going.',
        'icon' : <SettingIcon/>,
      },
    ],

  },
  {
    'title' : '2023 Q2',
    'content' : [
      {
        'subTitle' : '1.New Exchange Listings',
        'description' : 'Outreach & discussions with additional cryptocurrency exchanges to provide users with more options for trading the JOY token.',
        'icon' : <SettingIcon/>,
      },
      {
        'subTitle' : '2.Creator tokens',
        'description' : 'Creator tokens is a key financial, value capture and community growth primitive unlocked by Joystream. It allows creator to issue a fungible token which captures revenue generated by their channel, and distributes a share of it pro-rate to token holders. There are also complem...',
        'icon' : <Creator_tokenIcon/>,
      },
      {
        'subTitle' : '3.Content Infrastructure: Visibility',
        'description' : 'With greater utilization and scale, it has become clear that there is a need for better visibility into errors and performance levels at different layers of the infrastructure. This means both capturing data from the consumer and infrastructure layer, and also synthetic...',
        'icon' : <SettingIcon/>,
      },
      {
        'subTitle' : '4.Project Overview Dashboard',
        'description' : ' purpose built data-driven dashboard to explain the project’s current status, growth and market positioning. This will be on the main project website and make it easy & quick for people to understand how the platform is going.',
        'icon' : <SettingIcon/>,
      },
    ],

  },
];
